### ISSUE TITLE
Released into source repository?

### ISSUE THREAD

**Issue by davetcoleman** [atenpas/handle_detector#3]
Just a heads up, it appears you used `bloom` to release this ROS package into its own source repository, which I don't think you are suppose to do. Most notably, your README.md has a lot of extra noise in it now. Usually you create a new repo for releasing, in your case it would be `handle_detector-release`

**Comment by atenpas** [comment]
I'm not sure what you mean. https://github.com/atenpas/handle_detector-release does exist.

**Comment by davetcoleman** [comment]
Did you intend for your README to have all that release data in it?
https://github.com/atenpas/handle_detector/blob/master/README.md

For more info:
http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease#Creating_a_Release_Repository

But perhaps I am mistaken and you wanted to do this?

**Comment by atenpas** [comment]
I thought I followed the instructions from your link, and some step in there added stuff to the readme ... so, I assumed that's supposed to be so.

**Comment by davetcoleman** [comment]
I think you must have pasted in the wrong repo name during the bloom setup. Here's an example of a _release_ repository:

https://github.com/ros-gbp/ros_controllers-release

As opposed to its _source_ repository:

https://github.com/ros-controls/ros_controllers

Sorry for the confusion! Github user wjwwood could help if you need it.

**Comment by atenpas** [comment]
Yes, I think I remember passing in the wrong repo name. Thanks! Btw, your 2nd link is dead.

**Comment by davetcoleman** [comment]
Ah yes I forgot ros-controls is plural, fixed!
