### ISSUE TITLE
rviz not showing data

### ISSUE THREAD

**Issue by jsalfity** [atenpas/handle_detector#6]
Hi,
I'm not seeing the data in rviz. I'm referencing the instructions from step 6 of the [wiki](http://wiki.ros.org/handle_detector).

Rviz is not showing anything but the grid and I think I know why, but would like some reassurance and guidance if possible. Here's what I see in rviz after setting Fixed Frame to `camera_link`, PointCloud2 to `/localization/point_cloud` and MarkerArray to `localization/visualization_all_handles`
![screenshot from 2016-08-03 15 25 33](https://cloud.githubusercontent.com/assets/20803806/17384118/9bbe6232-598e-11e6-9d89-fe2df79390a6.png)

I would expect to see at least the point cloud data if localization did not recognize any handles

I'm launching an Xbox camera with `roslaunch freenect_launch freenect.launch.` At this point I don't have an actual robot running so I don't have anything else but the `camera_link` as a coordinate frame.

My output from `rosrun rqt_tf_tree rqt_tf_tree` (to view the /tf tree) looks like this:
![frames](https://cloud.githubusercontent.com/assets/20803806/17383765/9c7901e8-598c-11e6-98de-8eadf8bb8080.png)

My output from `rqt_graph` looks like this:
![rosgraph](https://cloud.githubusercontent.com/assets/20803806/17383540/51dc8598-598b-11e6-82a9-a603fd31d76e.png)

So...
I think I know why there is no output in rviz, its because there is no link between /tf and /localization. 

Can anybody drop any hints if I'm on the right track, if there are solutions out there or if I'm just plain way off.

Thanks!

**Comment by atenpas** [comment]
Can you see the point cloud if you look at the camera's point cloud topic, e.g., /camera/depth_registered/points (if this topic exists in your case)?

With respect to the handles/grasps, is there any terminal output that indicates that grasps/handles have been found?

**Comment by jsalfity** [comment]
@atenpas 
Yes, there are definitely images coming through the /camera/depth_registered/points topic when I use PointCloud2 in rviz. They are the point cloud images that I would expect.

When I try `$ rostopic echo /localization/handle_list` I get the message:
`ERROR: cannot load message class for [handle_detector/HandleListMsg]. Are your messages built?`

Even if handles haven't been found, I would still think I would be able to see the output from `/localization/point_cloud`. Did my hunch of the /localization not being connected to /tf raise any suspicion?

Thanks for the help!

**Comment by jsalfity** [comment]
Realized I wasn't subscribing to the topic `/camera/depth_registered/points` correctly
Worked.

**Comment by akhilmasetti1** [comment]
@jsalfity 

even im getting same error can u let me know where i went wrong
when i run point cloud i got like this
![Screenshot from 2019-03-30 23-32-57](https://user-images.githubusercontent.com/33285689/55279900-722dda80-5344-11e9-837c-ea463950ba07.png)
![Screenshot from 2019-03-30 23-34-25](https://user-images.githubusercontent.com/33285689/55279901-72c67100-5344-11e9-8eb9-9d8fb2ffc56a.png)
